# Generated by Django 2.2.8 on 2019-12-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('user_pw', models.TextField()),
                ('name', models.CharField(max_length=10)),
                ('birth_date', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=10)),
            ],
        ),
    ]
